# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('age', models.CharField(default='', max_length=5, null=True)),
                ('biography', models.CharField(default='', max_length=300, null=True)),
                ('avatar', models.ImageField(default='user-avatars/default_avatar.png', upload_to='user-avatars')),
                ('token', models.CharField(max_length=60, null=True)),
                ('reserve1', models.CharField(max_length=1, null=True)),
                ('reserve2', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
