# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default=b"#### Welcome to the markdown collaboration tool\n\n##### This is what you can do\n(Developed without third-part library support)\n* Create List\n   * Or create nested list by adding three whitespace (each nest level) at the beginning\n      * Like this\n* Inline syntax such as:\n   * **Bold** syntax\n   * __Underline__\n   * --Delete Line--\n   * [Hyper Text](google.com)\n* You can add a code block like this\n''' java\npublic static void resetTheWorld(int theAnswer){\n    int a = theAnswer;\n    return -a;\n}\n'''\n* We also support Image\n* ![](https://media.giphy.com/media/9gISqB3tncMmY/giphy.gif)\n\n(You can clear these text by click [this link](reset))\n\nFinally\n\n# Good job\n\n![](https://media.giphy.com/media/26ufkNFQ5mFJHeTu0/giphy.gif)")),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('last_saved_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.CharField(default=b'0', max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_doc', to=settings.AUTH_USER_MODEL)),
                ('shared_user', models.ManyToManyField(blank=True, related_name='shared_doc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
