
Message = {
  "000": "Success",
  "001": "Sign up successfully",
  "002": "Successfully Connect Websocket",
  "101": "Django Error",
  "102": "Username has been registered",
  "103": "Username should only contain digits!",
  "104": "Email has been registered",
  "105": "Illegal email format",
  "106": "Repeat password is not the same with origin password",
  "107": "Username or password wrong",
  "108": "User not active",
  "109": "Document Title could not be empty",
  "110": "Require document id",
  "111": "Cannot find document id",
  "112": "Not recognize request path",
  "113": "Malformed request",
  "114": "Nickname needed in chat request",
  "115": "Docid needed in chat request",
  "116": "User id needed in request",
  "117": "User not found",
  "118": "Indice error",
  "119": "Illegal docid",
  "120": "User not log in",
  "121": "Unsupported Request Method",
  "122": "Document has been deleted",
  "123": "Illegal Token",
  "124": "Email not found",
  "125": "Change password failed",
  "126": "Unsupported notification type",
  "127": "No such notification",
  "128": "Sending email failed",


  "999": "Unknow Error",
}
